const Map<String, String> ar = {
  // Intro
  'onboarding_title_1': 'تشكيلات رائعة',
  'onboarding_body_1': 'اكتشف مجموعة واسعة من الملابس الجديدة والمستعملة',
  'onboarding_title_2': 'تجربة سلسة',
  'onboarding_body_2': 'من التحويلات المالية الآمنة للتوصيل السريع',
  'onboarding_title_3': 'تسوق بكل ثقة',
  'onboarding_body_3': 'استمتع بأفضل العروض والأسعار التنافسية',
  'next': 'التالي',
  'get_started': 'ابدأ الآن',
  'skip': 'تخطي',
  'done': 'تم',

  // Auth
  'login': 'تسجيل الدخول',
  'signup': 'إنشاء حساب',
  'email_hint': 'أدخل البريد الإلكتروني',
  'password_hint': 'أدخل كلمة المرور',
  'welcome_back': 'مرحباً بك في أبو عهد',
  'store_name': 'متجر أبو عهد',
  'create_account_title': 'إنشاء حساب',
  'create_account_subtitle': 'انضم إلى السوق المتميز للأزياء الحصرية',
  'name': 'الاسم',
  'phone_number': 'رقم الهاتف',
  'address': 'العنوان',
  'name_placeholder': 'محمد أحمد',
  'address_placeholder': 'الشارع، المدينة، الدولة',
  'password': 'كلمة المرور',
  'password_placeholder': '••••••••',
  'register': 'تسجيل',
  'already_have_account': 'لديك حساب بالفعل؟ ',
  'no_account': 'ليس لديك حساب؟ ',
  'login_title': 'تسجيل الدخول',
  'login_subtitle': 'تسجيل الدخول إلى حسابك لمتابعة التسوق',
  'phone_required': 'رقم الهاتف مطلوب',
  'invalid_phone_format': 'تنسيق رقم الهاتف غير صالح (يدعم تركيا وسوريا)',
  'is_required': 'مطلوب',
  'login_failed': 'فشل تسجيل الدخول',
  'signup_failed': 'فشل إنشاء الحساب',

  // Categories
  'men': 'رجالي',
  'women': 'نسائي',
  'children': 'أطفال',
  'new_collection': 'تشكيلة جديدة',
  'used_items': 'ملابس مستعملة',

  // Product & Cart
  'add_to_cart': 'إضافة إلى السلة',
  'checkout': 'إتمام الشراء',
  'price': 'السعر',
  'total': 'الإجمالي',
  'cart_empty': 'سلة المشتريات فارغة',

  // Payment Flow
  'payment_method': 'تحويل بنكي',
  'upload_proof': 'إرفاق إيصال الدفع',
  'upload_proof_desc': 'يرجى رفع صورة من الحوالة البنكية لإكمال الطلب.',
  'submit_order': 'تأكيد الطلب',
  'order_success': 'تم إرسال الطلب بنجاح!',
};
