const Map<String, String> ar = {
  // Intro
  'onboarding_title_1': 'تشكيلات رائعة',
  'onboarding_body_1': 'اكتشف مجموعة واسعة من الملابس الجديدة والمستعملة',
  'onboarding_title_2': 'تجربة سلسة',
  'onboarding_body_2': 'من التحويلات المالية الآمنة للتوصيل السريع',
  'onboarding_title_3': 'تسوق بكل ثقة',
  'onboarding_body_3': 'استمتع بأفضل العروض والأسعار التنافسية',
  'next': 'التالي',
  'get_started': 'ابدأ الآن',
  'skip': 'تخطي',
  'done': 'تم',

  // Auth
  'login': 'تسجيل الدخول',
  'signup': 'إنشاء حساب',
  'email_hint': 'أدخل البريد الإلكتروني',
  'password_hint': 'أدخل كلمة المرور',
  'welcome_back': 'مرحباً بك في أبو عهد',
  'store_name': 'متجر أبو عهد',
  'create_account_title': 'إنشاء حساب',
  'create_account_subtitle': 'انضم إلى السوق المتميز للأزياء الحصرية',
  'name': 'الاسم',
  'phone_number': 'رقم الهاتف',
  'address': 'العنوان',
  'address_required': 'العنوان مطلوب',
  'name_placeholder': 'محمد أحمد',
  'address_placeholder': 'الشارع، المدينة، الدولة',
  'password': 'كلمة المرور',
  'password_placeholder': '••••••••',
  'confirm_password': 'تأكيد كلمة المرور',
  'confirm_password_placeholder': '••••••••',
  'register': 'تسجيل',
  'already_have_account': 'لديك حساب بالفعل؟ ',
  'no_account': 'ليس لديك حساب؟ ',
  'login_title': 'تسجيل الدخول',
  'login_subtitle': 'تسجيل الدخول إلى حسابك لمتابعة التسوق',
  'phone_required': 'رقم الهاتف مطلوب',
  'invalid_phone_format': 'تنسيق رقم الهاتف غير صالح (يدعم تركيا وسوريا)',
  'is_required': 'مطلوب',
  'login_failed': 'فشل تسجيل الدخول',
  'signup_failed': 'فشل إنشاء الحساب',
  'passwords_do_not_match': 'كلمات المرور غير متطابقة',
  'role': 'الدور',
  'customer': 'زبون',
  'admin': 'مدير',
  'delivery': 'موصل',
  'logout': 'تسجيل الخروج',

  // Profile
  'profile': 'الملف الشخصي',

  // Categories
  'men': 'رجالي',
  'women': 'نسائي',
  'children': 'أطفال',
  'new_collection': 'تشكيلة جديدة',
  'used_items': 'ملابس مستعملة',

  // Product & Cart
  'add_to_cart': 'إضافة إلى السلة',
  'checkout': 'إتمام الشراء',
  'price': 'السعر',
  'total': 'الإجمالي',
  'cart_empty': 'سلة المشتريات فارغة',
  'description': 'الوصف',
  'only_x_left_in_stock': 'فقط @count متبقي في المخزون!',
  'out_of_stock': 'نفذت الكمية',
  'success': 'نجح',
  'error': 'خطأ',

  // Payment Flow
  'payment_method': 'تحويل بنكي',
  'upload_proof': 'إرفاق إيصال الدفع',
  'upload_proof_desc': 'يرجى رفع صورة من الحوالة البنكية لإكمال الطلب.',
  'submit_order': 'تأكيد الطلب',
  'order_success': 'تم إرسال الطلب بنجاح!',

  // Admin - Product Management
  'products': 'المنتجات',
  'add_product': 'إضافة منتج',
  'create_product': 'إنشاء منتج',
  'product_title': 'اسم المنتج',
  'enter_product_title': 'أدخل اسم المنتج',
  'enter_price': 'أدخل السعر',
  'enter_description': 'أدخل الوصف',
  'enter_stock': 'أدخل الكمية',
  'condition': 'الحالة',
  'category': 'الفئة',
  'size': 'المقاس',
  'stock': 'المخزون',
  'delete_product': 'حذف المنتج',
  'confirm_delete_product': 'هل أنت متأكد من حذف هذا المنتج؟',
  'delete': 'حذف',
  'cancel': 'إلغاء',
  'field_required': 'هذا الحقل مطلوب',
  'invalid_price': 'يرجى إدخال سعر صحيح',
  'invalid_stock': 'يرجى إدخال رقم صحيح',
  'suits': 'بدلات',

  // Home Screen
  'home_title': 'أبو عهد',
  'all_products': 'عرض الكل',
  'new_arrivals': 'وصل حديثاً',
  'rare_pieces': 'قطع نادرة',
  'premium_brand': 'أبو عهد بريميوم',
  'no_products_found': 'لم يتم العثور على قطع',
  'show_all_products': 'عرض كل القطع',
  'loading_products': 'جاري تحميل المنتجات...',
  'error_loading_products': 'حدث خطأ أثناء تحميل المنتجات',
  'retry': 'إعادة المحاولة',

  // Categories
  'summer': 'صيفي',
  'autumn': 'خريفي',
  'accessories': 'إكسسوارات',
  'formal': 'رسمي',
  'watches': 'ساعات',
  'shoes': 'أحذية',

  // Product Condition
  'new': 'جديد',
  'used': 'مستعمل',

  // Cart Screen
  'cart_title': 'سلتي',
  'items_selected': 'تم اختيار @count عناصر',
  'enter_coupon': 'أدخل رمز القسيمة',
  'apply': 'تطبيق',
  'subtotal': 'المجموع الفرعي',
  'shipping': 'الشحن',
  'free': 'مجاني',
  'tax_included': 'شامل الضريبة',
  'continue_checkout': 'المتابعة للدفع',
  'secure_payment': 'دفع آمن ومشفر',
  'cart_failed': 'فشل تحميل السلة',
  'start_shopping': 'ابدأ التسوق الآن',
  'remove_item': 'حذف',
  'orders': 'الطلبات',
  'no_orders_found': 'لا توجد طلبات',
  'no_order_history_found': 'لا يوجد طلبات سابقة',
  'active_orders': 'نشطة',
  'order_history': 'السجل',
  'status': 'الحالة',

  // Orders
  'order_placed_success': 'تم تقديم الطلب بنجاح',
  'order_create_failed': 'فشل في إنشاء الطلب',
  'payment_image_uploaded': 'تم رفع صورة الدفع بنجاح',
  'payment_image_upload_failed': 'فشل في رفع صورة الدفع',
  'order_confirmed_success': 'تم تأكيد الطلب بنجاح',
  'order_confirm_failed': 'فشل في تأكيد الطلب',
  'payment_verified': 'تم التحقق من الدفع',
  'payment_verify_failed': 'فشل في التحقق من الدفع',
  'pending_payments_failed': 'فشل في تحميل المدفوعات المعلّقة',
  'delivery_confirmed_success': 'تم تأكيد التوصيل بنجاح',
  'delivery_confirm_failed': 'فشل في تأكيد التوصيل',
  'active_orders_failed': 'فشل في تحميل الطلبات النشطة',
  'order_history_failed': 'فشل في تحميل سجل الطلبات',
};
