const Map<String, String> en = {
  // Intro
  'onboarding_title_1': 'Wonderful Collections',
  'onboarding_body_1': 'Discover a wide range of new and used clothes',
  'onboarding_title_2': 'Seamless Experience',
  'onboarding_body_2': 'From secure payments to fast delivery',
  'onboarding_title_3': 'Shop with Confidence',
  'onboarding_body_3': 'Enjoy the best offers and competitive prices',
  'next': 'Next',
  'get_started': 'Get Started',
  'skip': 'Skip',
  'done': 'Done',

  // Auth
  'login': 'Login',
  'signup': 'Sign Up',
  'email_hint': 'Enter your email',
  'password_hint': 'Enter your password',
  'welcome_back': 'Welcome Back to Abu Ahed',
  'store_name': 'Abu Ahed Store',
  'create_account_title': 'Create Account',
  'create_account_subtitle': 'Join the exclusive fashion premium market',
  'name': 'Name',
  'phone_number': 'Phone Number',
  'address': 'Address',
  'address_required': 'Address is required',
  'name_placeholder': 'Mohamad Ahmed',
  'address_placeholder': 'Street, City, Country',
  'password': 'Password',
  'password_placeholder': '••••••••',
  'confirm_password': 'Confirm Password',
  'confirm_password_placeholder': '••••••••',
  'register': 'Register',
  'already_have_account': 'Already have an account? ',
  'no_account': 'Don\'t have an account? ',
  'login_title': 'Login',
  'login_subtitle': 'Login to your account to continue shopping',
  'phone_required': 'Phone number is required',
  'invalid_phone_format': 'Invalid phone format (Turkey & Syria supported)',
  'is_required': 'is required',
  'login_failed': 'Login failed',
  'signup_failed': 'Signup failed',
  'passwords_do_not_match': 'Passwords do not match',

  // Categories
  'men': 'Men',
  'women': 'Women',
  'children': 'Children',
  'kids': 'Kids',
  'new_collection': 'New Collection',
  'used_items': 'Used Items',

  // Product & Cart
  'add_to_cart': 'Add to Cart',
  'checkout': 'Checkout',
  'price': 'Price',
  'total': 'Total',
  'cart_empty': 'Your cart is empty',
  'description': 'Description',
  'only_x_left_in_stock': 'Only @count left in stock!',
  'out_of_stock': 'Out of Stock',
  'new': 'New',
  'used': 'Used',
  'success': 'Success',
  'error': 'Error',
  'retry': 'Retry',

  // Cart Screen
  'cart_title': 'My Cart',
  'items_selected': 'Selected @count items',
  'enter_coupon': 'Enter coupon code',
  'apply': 'Apply',
  'subtotal': 'Subtotal',
  'shipping': 'Shipping',
  'free': 'Free',
  'tax_included': 'Tax included',
  'continue_checkout': 'Continue to Checkout',
  'secure_payment': 'Secure encrypted payment',
  'cart_failed': 'Failed to load cart',
  'start_shopping': 'Start shopping now',
  'remove_item': 'Remove',
  'orders': 'Orders',
  'no_orders_found': 'No orders found',
  'no_order_history_found': 'No order history found',
  'active_orders': 'Active',
  'order_history': 'History',
  'status': 'Status',
  'order_status_pending': 'Pending',
  'order_status_confirmed': 'Confirmed',
  'order_status_payment_under_review': 'Payment Under Review',
  'order_status_processing': 'Processing',
  'order_status_on_way': 'On the Way',
  'order_status_delivered': 'Delivered',
  'order_status_cancelled': 'Cancelled',

  // Payment Flow
  'payment_method': 'Bank Transfer',
  'upload_proof': 'Upload Payment Receipt',
  'upload_proof_desc':
      'Please upload a screenshot of your bank transfer to complete the order.',
  'submit_order': 'Submit Order',
  'order_success': 'Order Submitted Successfully!',

  // Admin - Product Management
  'products': 'Products',
  'add_product': 'Add Product',
  'create_product': 'Create Product',
  'update_product': 'Update Product',
  'product_title': 'Product Title',
  'enter_product_title': 'Enter product title',
  'enter_price': 'Enter price',
  'enter_description': 'Enter description',
  'enter_stock': 'Enter stock quantity',
  'condition': 'Condition',
  'category': 'Category',
  'size': 'Size',
  'stock': 'Stock',
  'delete_product': 'Delete Product',
  'confirm_delete_product': 'Are you sure you want to delete this product?',
  'delete': 'Delete',
  'cancel': 'Cancel',
  'field_required': 'This field is required',
  'invalid_price': 'Please enter a valid price',
  'invalid_stock': 'Please enter a valid number',
  'suits': 'Suits',
  'no_products_found': 'No products found',
  'products_load_failed': 'Failed to load products',
  'product_details_load_failed': 'Failed to load product details',
  'product_created_successfully': 'Product created successfully',
  'product_create_failed': 'Failed to create product',
  'product_updated_successfully': 'Product updated successfully',
  'product_update_failed': 'Failed to update product',
  'product_deleted_successfully': 'Product deleted successfully',
  'product_delete_failed': 'Failed to delete product',
  'product_added_to_cart': 'Product added to cart',
  'add_to_cart_failed': 'Failed to add to cart',

  // Orders
  'order_placed_success': 'Order placed successfully',
  'order_create_failed': 'Failed to create order',
  'payment_image_uploaded': 'Payment image uploaded successfully',
  'payment_image_upload_failed': 'Failed to upload payment image',
  'order_confirmed_success': 'Order confirmed successfully',
  'order_confirm_failed': 'Failed to confirm order',
  'payment_verified': 'Payment verified',
  'payment_verify_failed': 'Failed to verify payment',
  'pending_payments_failed': 'Failed to load pending payments',
  'delivery_confirmed_success': 'Delivery confirmed successfully',
  'delivery_confirm_failed': 'Failed to confirm delivery',
  'active_orders_failed': 'Failed to load active orders',
  'order_history_failed': 'Failed to load order history',
  //roles
  'Customer': 'Customer',
  'Admin': 'Admin',
  'Courier': 'Courier',

  // Media / Image Picker
  'product_images': 'Product Images',
  'product_media': 'Product Media',
  'add_images': 'Add Images',
  'add_media': 'Add Images & Videos',
  'gallery': 'Gallery',
  'camera': 'Camera',
  'take_photo': 'Take Photo',
  'record_video': 'Record Video',
  'images_and_videos': 'Images & Videos',
  'max_images_reached': 'Maximum number of images reached',
  'max_files_reached': 'Maximum number of files reached',
  'file_too_large': 'File exceeds 10 MB limit',
};
