const Map<String, String> en = {
  // Intro
  'onboarding_title_1': 'Wonderful Collections',
  'onboarding_body_1': 'Discover a wide range of new and used clothes',
  'onboarding_title_2': 'Seamless Experience',
  'onboarding_body_2': 'From secure payments to fast delivery',
  'onboarding_title_3': 'Shop with Confidence',
  'onboarding_body_3': 'Enjoy the best offers and competitive prices',
  'next': 'Next',
  'get_started': 'Get Started',
  'skip': 'Skip',
  'done': 'Done',

  // Auth
  'login': 'Login',
  'signup': 'Sign Up',
  'email_hint': 'Enter your email',
  'password_hint': 'Enter your password',
  'welcome_back': 'Welcome Back to Abu Ahed',
  'store_name': 'Abu Ahed Store',
  'create_account_title': 'Create Account',
  'create_account_subtitle': 'Join the exclusive fashion premium market',
  'name': 'Name',
  'phone_number': 'Phone Number',
  'address': 'Address',
  'name_placeholder': 'Mohamad Ahmed',
  'address_placeholder': 'Street, City, Country',
  'password': 'Password',
  'password_placeholder': '••••••••',
  'confirm_password': 'Confirm Password',
  'confirm_password_placeholder': '••••••••',
  'register': 'Register',
  'already_have_account': 'Already have an account? ',
  'no_account': 'Don\'t have an account? ',
  'login_title': 'Login',
  'login_subtitle': 'Login to your account to continue shopping',
  'phone_required': 'Phone number is required',
  'invalid_phone_format': 'Invalid phone format (Turkey & Syria supported)',
  'is_required': 'is required',
  'login_failed': 'Login failed',
  'signup_failed': 'Signup failed',
  'passwords_do_not_match': 'Passwords do not match',

  // Categories
  'men': 'Men',
  'women': 'Women',
  'children': 'Children',
  'new_collection': 'New Collection',
  'used_items': 'Used Items',

  // Product & Cart
  'add_to_cart': 'Add to Cart',
  'checkout': 'Checkout',
  'price': 'Price',
  'total': 'Total',
  'cart_empty': 'Your cart is empty',
  'description': 'Description',
  'only_x_left_in_stock': 'Only @count left in stock!',
  'out_of_stock': 'Out of Stock',
  'new': 'New',
  'used': 'Used',
  'success': 'Success',
  'error': 'Error',
  'retry': 'Retry',

  // Payment Flow
  'payment_method': 'Bank Transfer',
  'upload_proof': 'Upload Payment Receipt',
  'upload_proof_desc':
      'Please upload a screenshot of your bank transfer to complete the order.',
  'submit_order': 'Submit Order',
  'order_success': 'Order Submitted Successfully!',
};
